### ISSUE TITLE
CORS error

### ISSUE THREAD

**Issue by fskinner** [velocityzen/meta-extractor#3]
Trying to extract from an external site returns me:

> MLHttpRequest cannot load "site-url". No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'localhost-url' is therefore not allowed access.

Is there any workaround?

**Comment by velocityzen** [comment]
@fskinner  What do you mean by external site? Are you using it from the browser?

**Comment by fskinner** [comment]
Yeah since my backend is not node. I've already changed the solution to the backend though

**Comment by velocityzen** [comment]
👍
