### ISSUE TITLE
support for google maps and request timeout functionality

### ISSUE THREAD

**Issue by fzp01717** [velocityzen/meta-extractor#5]
Hello, great work. can you please provide support for google maps meta tags. it is currently not parsing google maps meta tags. i am providing a url with facebook open graph result and your application result and please add timeout functionality.Thanks
URL: https://www.google.com.bd/maps/place/Shaheed+Suhrawardy+Medical+College+and+Hospital/@23.7688139,90.360714,15z/data=!4m5!3m4!1s0x0:0x515136eca08d1278!8m2!3d23.769162!4d90.3710112?hl=en

FaceBook:

![capture3](https://user-images.githubusercontent.com/9360179/31032005-4bba2cfe-a57c-11e7-85f6-367c7f05a9e7.PNG)

meta-extractor: 

![capture4](https://user-images.githubusercontent.com/9360179/31032006-4bba5ce2-a57c-11e7-8b1a-51eb544cbc75.PNG)

**Comment by velocityzen** [comment]
Hey! Thanks

It supports timeouts. Meta-extractor uses [got](https://github.com/sindresorhus/got) internally and supports all the options it has. 

Google Maps doesn't provide any other tags with its pages. As facebook link lint says they **constructed** them. So you can do it too. Meta extractor only extracts what page has. 

👌

**Comment by fzp01717** [comment]
Hi. i just change the USERAGENT = `meta-extractor/${VERSION} (https://github.com/velocityzen/meta-extractor)`;  to USERAGENT = 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36';  and the output changes from image1 to image2 which i am seeking for :)
image 1:
![capture4](https://user-images.githubusercontent.com/9360179/31044199-9d287904-a5ec-11e7-8ce9-1691cbbd17b6.PNG)
Image 2:
![capture5](https://user-images.githubusercontent.com/9360179/31044205-b2cb5dc6-a5ec-11e7-83c6-67420a09ea6a.PNG)

**Comment by fzp01717** [comment]
Hi brother. i changed the USERAGENT variable value from `meta-extractor/${VERSION} (https://github.com/velocityzen/meta-extractor)` to 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.98 Mobile Safari/537.36' and the output changes from image1 to image2 which i am seeking for the google maps url i provided. Thanks.

image1:
![capture](https://user-images.githubusercontent.com/9360179/31052601-cf4b30b6-a6aa-11e7-9f7f-2e8f7595360c.PNG)
image2:   
![capture2](https://user-images.githubusercontent.com/9360179/31052604-d5aaf720-a6aa-11e7-9bba-36332e602574.PNG)

**Comment by velocityzen** [comment]
@fzp01717 You don't need to change it in the code, you can provide it with options:
```js
extract({ 
  uri: 'https://www.google.com.bd/maps/place/Shaheed+Suhrawardy+Medical+College+and+Hospital/@23.7688139,90.360714,15z/data=!4m5!3m4!1s0x0:0x515136eca08d1278!8m2!3d23.769162!4d90.3710112?hl=en',
  headers: { 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.98 Mobile Safari/537.36' }
}, (err, res) =>
  console.log('page', err, res)
);

```

**Comment by fzp01717** [comment]
Brother it will be better if you provide a detail documentation about the parameters and the other external functionality in the readme.md file. otherwise developer like us will feel little bit confused when using the plugin.It is a great work. you can see here what i have build using your plugin.just click this url http://52.15.120.187/im-messenger/ . login and pest a  url like youtube, soundcloud, maps any thing in the message box and see what happens. That's why i need a clear documentation. thanks :)

**Comment by fzp01717** [comment]
i also found a problem about the error of a website. if i provide this url http://www.smsport.xyz it didn't give me any error in the console. it prints nothing.if i change the code from
.on('error', err => {
      error = err;
    })

to

.on('error', err => {
      error = err;
      done(error, null)
    })

it is giving me the desired error.

**Comment by velocityzen** [comment]
That was a good one, thanks! Fixed and published!

There is a line in documentation 'The first parameter opts as in got module' so if you click on got you'll see all the parameters. There are parameters from external module, not from this one.

**Comment by fzp01717** [comment]
oh. ok brother :)

**Comment by fzp01717** [comment]
brother it will be great if you provide image type beside every image url in image set. 
![capture](https://user-images.githubusercontent.com/9360179/31574151-6f6c3aa0-b0eb-11e7-8ed2-d5e03f0cca52.PNG)

or can you suggest me any library which can help me filter out jpg/png images from this image set ?? as you can see in the picture there is a url contain .png extension in last. i only want this url in a quick way.

**Comment by velocityzen** [comment]
The purpose of this module is to provide **page** meta information as fast as possible.
You ask to provide image **files/links** meta information, that means + one request for every file/link. This is neither what the library made for nor the fastest way to get meta info.

**Comment by fzp01717** [comment]
Brother in this module they have provided the images width and height. 

https://github.com/samholmes/node-open-graph

And in this module they provided the big description of a page. 

https://github.com/gabceb/node-metainspector

Can you marge this facility in your code that if the meta image or description is not provided than your code find the big image and description from a url.

**Comment by velocityzen** [comment]
@fzp01717 
https://github.com/samholmes/node-open-graph
Provides width and height **only** if it is in the html tag. This is a very rare condition and leads to inconsistency.

What do you mean by: `if the meta image or description is not provided than your code find the big image and description from a url.`?

I'll add feeds though. Thanks

**Comment by fzp01717** [comment]
Brother like facebook, if the ogimage or ogdescription tag is missing from a webpage it extract the the first big image and the first big description. Is there any way you can add this feature in your code? Like If there is no description or image meta tag is present in a html page for both tweeter and Facebook,  your code finds the big image and description. Thanks

**Comment by velocityzen** [comment]
How do you define big image and big description? This lib doesn't know sizes of the pictures. 
What are you trying to achieve? It isn't a content parsing library. 

Added feeds extracting and promises support.

**Comment by fzp01717** [comment]
Then i think i have to do it by myself. thanks brother. thanks for your quick reply and also providing a awesome library.
