### ISSUE TITLE
Does meta-extractor protect for LARGE html files?

### ISSUE THREAD

**Issue by ibc** [velocityzen/meta-extractor#6]
Let's assume I have a 2GB file called `index.html` in my web server, and my HTTP server serves it with common `Content-Type: text/html`, so everything looks good.

If I pass such a link (`http://mydomain/index.html`) to the `extract()` function of meta-extractor, will it attempt to download 2GB of data?

Obviously this is something like an attack. Does meta-extractor prevent it by limiting the total HTML file size or something similar?

**Comment by velocityzen** [comment]
Hello @ibc 
Now it has!
Since v1.4.0 use the `limit` option.
Thanks for suggestion.

**Comment by ibc** [comment]
G-R-E-A-T
Thanks!
