### ISSUE TITLE
await is only valid in async function

### ISSUE THREAD

**Issue by SweetVinegar** [velocityzen/meta-extractor#9]
great project.

I have a problem with the second way.  I got "await is only valid in async function" when I use 

await extract({ uri: url});

**Comment by velocityzen** [comment]
thank you. Top level `await` doesn't work in v8 yet. You can wrap it in immediately invoked function expression, or IIFE

```js
(async () => {
  // code goes here
  const res = await extract({ uri: url});
})();
```
